# Generated by Django 4.2 on 2025-05-13 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0002_equipment_plantingplan_purchase_tree_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image_url", models.URLField()),
                ("article_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("notification_date", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("location_type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserPlanting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planting_date", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.plantinglocation",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="image",
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="tree",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="image",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="preferred_area",
        ),
        migrations.RemoveField(
            model_name="tree",
            name="species",
        ),
        migrations.AddField(
            model_name="equipment",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tree",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tree",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="tree",
            name="description",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="PlantingPlan",
        ),
        migrations.AddField(
            model_name="userplanting",
            name="tree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.tree"
            ),
        ),
        migrations.AddField(
            model_name="userplanting",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
