# Generated by Django 4.2 on 2025-05-17 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_treeorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.plantinglocation",
            ),
        ),
    ]
