# Generated by Django 4.2 on 2025-05-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_purchase_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(max_length=20)),
                ("item_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="NewsArticle",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="quantity",
        ),
        migrations.DeleteModel(
            name="TreeOrder",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="myapp.purchase",
            ),
        ),
    ]
