# Generated by Django 4.2 on 2025-05-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_orderitem_delete_newsarticle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
