# Generated by Django 4.2 on 2025-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_treeorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
