# Generated by Django 4.2 on 2025-05-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_orderitem_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchase",
            name="tel",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
